<?php

namespace App\Services;

use Illuminate\Support\Facades\Facade;

class JalaliDate extends Facade
{
    protected static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'JalaliDateService';
    }

}
